version: '3.9'
services:
  reverse_proxy:
    image: nginx
    init: true
    links: 
      - "syncplay"
    ports:
      - "80:80"
      - "443:443"
      - "8999:8999/tcp"
    volumes:
      - ./config:/etc/nginx/conf.d/
      - ./pages:/var/www/html/
      - ./includes:/etc/nginx/includes/
      - ./ssl_files:/etc/ssl/certs/nginx/
    network_mode: "bridge"

  syncplay:
    image: ninetaillabs/syncplay-server
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    expose:
      - "8999"
    network_mode: "bridge"
    environment:
      - PASSWORD: "Pinguino1"
      - PORT: 8999
      - TLS: "/certs"
      - SALT: "DhP2da8vWdWf"
    volumes:
      - ./ssl_files:/certs
    depends_on:
      - reverse_proxy